---
# example tasks
resources:
- name: azs-concourse
  type: git
  source: 
    uri: https://github.com/bottkars/azs-concourse
    branch: master
    private_key: ((azs-resource-key.private_key))

- name: azs-powershell
  #icon: amazon-drive
  type: docker-image
  source:
   repository: bottkars/azs-powershell
   username: bottkars
   password: Breda1208

jobs:
- name: test-powershell 
  plan:
  - get: azs-concourse
    trigger: true
  - get: azs-powershell
    trigger: true
    params:
        save: false
        rootfs: false
        skip_download: true
  - task: test-powershell
    file: azs-concourse/ci/powershell/tasks/test-task.yml
    # image: azure-stack-powershell
