resources:
- name: azurestack-powershell-image
  type: s3
  source:
    bucket: image
    regexp: azure-stack-powershell-(.*).tgz
    access_key_id: ((access_key_id))
    endpoint:  ((s3_endpoint))
    region_name: ((s3_region_name))
    secret_access_key: ((secret_access_key))

jobs:
- name: imagefrom-sr3
  plan:
  - get: azurestack-powershell-image
    params:
      unpack: true
  - task: run-with-image-from-s3-using-resource-definition
    image: azurestack-powershell-image
    config:
      platform: windows
      run:
        path: powershell.exe
        args:
        - get-computerinfo
