---
name: ((minio.deployment_name))
releases:
- name: minio
  version: 2019-10-12T01-39-57Z+dev.7

stemcells:
- alias: default
  os: ubuntu-bionic
  version: ((minio.stemcell-release))


instance_groups:
- name: minio
  azs: ((azs))
  instances: 1
  jobs:
  - name: minio-azure
    release: minio
    templates:
    - name: minio-azure
    properties:
      credential:
        accesskey: ((minio.azure.accesskey))
        secretkey: ((minio.azure.secretkey))
      port: ((minio.port))
      custom_endpoint: ((minio.azure.endpoint_suffix))
      ca_cert: ((minio.azure.ca_cert))
  networks:
  - name: ((network_name))
  vm_type: ((minio.vm_type))
  stemcell: default

update:
  canaries: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 2 
