---
name: ((minio_deployment_name))
releases:
- name: minio
  version: latest

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

variables:
- name: minio_accesskey
  type: password
- name: minio_secretkey
  type: password

instance_groups:
- name: minio
  azs: ((azs))
  instances: 1
  jobs:
  - name: minio-azure
    release: minio
    templates:
    - name: minio-azure
    properties:
      credential:
        accesskey: ((minio_accesskey))
        secretkey: ((minio_secretkey))
      port: 9000
  networks:
  - name: ((network_name))
  vm_type: ((vm_type))
  stemcell: default

update:
  canaries: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 2
